# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright © 2026 Enrico Weigelt, metux IT consult

mpbt_git:     git@github.com:mpbt-hq/mpbt.git

install-prefix: ${@PROJECT::@workdir}/target

build:
    - mpbt

packages:
    - ${@PROJECT::@rootdir}/cf/mpbt/packages

package-defaults:
    mpbt_git:     ${mpbt_git}
