#!/bin/sh
#
# List all open PRs that have merge conflicts.
#
# Uses the GitHub CLI to query up to 100 open PRs and filters for those
# whose mergeable status is "CONFLICTING". Output format:
#
#   <number>: (<author>) <title> - <author>
#

gh pr list --limit 100 --json number,author,title,mergeable --jq '.[] | select(.mergeable == "CONFLICTING") | "\(.number): (\(.author.login)) \(.title) - \(.author.login)"'
